language: swift
osx_image: xcode10.1
xcode_project: libxmpp.xcodeproj
xcode_scheme: libxmpp
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS

script:
  - env
  - swiftlint --strict --quiet
  - set -o pipefail && xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -destination "$XCODE_DESTINATION" build test | xcpretty
